# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 222333563a57d7703aa53c8e88592777fb5c60987b1ee744f9a4fcea4281613c8f200d3623ccf8941337ac292451e106450f48f76c3263d5deba1678c72daec2

test:
  secret_key_base: fa9d5962baef195bcf9f90c701b70718b3088e2ce07da59c5257d2c43813b17f08aa5d5ddc0b483c90c82b9bcfb6f8c19620b477de79a736cd006b12482c84f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
